apiVersion: v1
kind: Service
metadata:
  name: sb-web-sample-01-docker-alpha1
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    run: sb-web-sample-01-docker-alpha1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: sb-web-sample-01-docker-alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-web-sample-01-docker-alpha1
spec:
  selector:
    matchLabels:
      run: sb-web-sample-01-docker-alpha1
  replicas: 1
  template:
    metadata:
      labels:
        run: sb-web-sample-01-docker-alpha1
    spec:
      containers:
      - name: sb-web-sample-01-docker-alpha1
        image: qooacr01.azurecr.io/sb-web-sample-01-docker-alpha1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: qooacr01